### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by pawelk1337** [benbaptist/wrapper.py#18]
Tried on Windows/Linux (kali)

```                                                                   
┌──(ash㉿ash-dev)-[~/mcserver]
└─$ export PATH=$PATH:~/.local/bin

                                                                            
┌──(ash㉿ash-dev)-[~/mcserver]
└─$ mcwrapper
Traceback (most recent call last):
  File "/home/ash/.local/bin/mcwrapper", line 2, in <module>
    from wrapper import Wrapper
  File "/home/ash/.local/lib/python3.10/site-packages/wrapper/__init__.py", line 13, in <module>
    from wrapper.server import Server
  File "/home/ash/.local/lib/python3.10/site-packages/wrapper/server/__init__.py", line 7, in <module>
    from wrapper.server.mcserver import MCServer
  File "/home/ash/.local/lib/python3.10/site-packages/wrapper/server/mcserver/__init__.py", line 10, in <module>
    from wrapper.server.mcserver.console_parser import ConsoleParser
  File "/home/ash/.local/lib/python3.10/site-packages/wrapper/server/mcserver/console_parser/__init__.py", line 7, in <module>
    from wrapper.server.world import World
  File "/home/ash/.local/lib/python3.10/site-packages/wrapper/server/world/__init__.py", line 4, in <module>
    from nbt.world import WorldFolder
  File "/home/ash/.local/lib/python3.10/site-packages/nbt/__init__.py", line 2, in <module>
    from . import *
  File "/home/ash/.local/lib/python3.10/site-packages/nbt/nbt.py", line 7, in <module>
    from collections import MutableMapping, MutableSequence, Sequence
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
idk why it snot working 
java 18 mc 1.18.2

**Comment by pawelk1337** [comment]
Works now 
soluton:
update pkg NBT
```
pip3 uninstall NBT
pip3 install NBT
```
