### ISSUE TITLE
Empty world or unknown world folder

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/wrapper.py#6]
The server crashes and will not run with a fresh install. If I manually run the minecraft server with ```java -jar server.jar``` and then rerun the wrapper it works. Well at least it boots up. I'm going to test functionality and plugins in a bit.

```
python start-wrapper.py 
[03:49:39] [Wrapper/main/INFO] Wrapper starting (0.0.5dev)
> [03:49:39] [Wrapper/mcserver/INFO] Starting server
['java', '-Xms1024M', '-Xmx2048M', '-jar', 'server.jar', 'nogui']
Serving on http://localhost:8025
[03:49:42] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[03:49:43] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:49:43] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:49:43] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:49:43] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:49:43] [main/INFO]: Reloading ResourceManager: Default
[03:49:43] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:49:43] [Worker-Main-14/INFO]: Loaded 7 recipes
[03:49:44] [Worker-Main-14/INFO]: Loaded 927 advancements
[03:49:45] [Server thread/INFO]: Starting minecraft server version 1.16.3
[03:49:45] [Server thread/INFO]: Default game type: SURVIVAL
[03:49:45] [Server thread/INFO]: Loading properties
[03:49:45] [Server thread/INFO]: Generating keypair
[03:49:45] [Server thread/INFO]: Starting Minecraft server on *:1337
[03:49:45] [Server thread/INFO]: Using epoll channel type
[03:49:45] [Wrapper/main/ERROR] Fatal error, shutting down
[03:49:45] [Wrapper/main/ERROR] Traceback (most recent call last):
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/__init__.py", line 122, in run
[03:49:45] [Wrapper/main/ERROR]     self.tick()
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/__init__.py", line 141, in tick
[03:49:45] [Wrapper/main/ERROR]     self.server.tick()
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/__init__.py", line 218, in tick
[03:49:45] [Wrapper/main/ERROR]     self.mcserver.tick()
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/__init__.py", line 234, in tick
[03:49:45] [Wrapper/main/ERROR]     if self.console_parser.parse(line) != False:
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/console_parser/__init__.py", line 22, in parse
[03:49:45] [Wrapper/main/ERROR]     self.new_style(new_style)
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/console_parser/__init__.py", line 54, in new_style
[03:49:45] [Wrapper/main/ERROR]     self.mcserver.world = World(r.group(1))
[03:49:45] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/world/__init__.py", line 13, in __init__
[03:49:45] [Wrapper/main/ERROR]     self.world = WorldFolder(level_name)
[03:49:45] [Wrapper/main/ERROR]   File "/usr/lib/python3.8/site-packages/nbt/world.py", line 257, in __call__
[03:49:45] [Wrapper/main/ERROR]     raise UnknownWorldFormat("Empty world or unknown format: %r" % world_folder)
[03:49:45] [Wrapper/main/ERROR] NameError: name 'world_folder' is not defined
[03:49:45] [Wrapper/main/ERROR] 
[03:49:45] [Wrapper/main/INFO] Wrapper has stopped

```

**Comment by benbaptist** [comment]
Oh yikes! Is this running the "stable" branch or the development branch? (I put "stable" in quotation marks because nothing is really stable yet!)

**Comment by l33tlinuxh4x0r** [comment]
Both versions have the same error.

**Comment by benbaptist** [comment]
Should be fixed in the latest source!
