### ISSUE TITLE
changing gamemode with /gamemode creative crashes the server

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/wrapper.py#7]
below is a log of the crash.

```<wrapper.server.player.Player object at 0x7f75693c3130> Set own game mode to Creative Mode
[03:58:23] [Wrapper/main/ERROR] Fatal error, shutting down
[03:58:23] [Wrapper/main/ERROR] Traceback (most recent call last):
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/__init__.py", line 122, in run
[03:58:23] [Wrapper/main/ERROR]     self.tick()
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/__init__.py", line 141, in tick
[03:58:23] [Wrapper/main/ERROR]     self.server.tick()
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/__init__.py", line 218, in tick
[03:58:23] [Wrapper/main/ERROR]     self.mcserver.tick()
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/__init__.py", line 234, in tick
[03:58:23] [Wrapper/main/ERROR]     if self.console_parser.parse(line) != False:
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/console_parser/__init__.py", line 22, in parse
[03:58:23] [Wrapper/main/ERROR]     self.new_style(new_style)
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/console_parser/__init__.py", line 142, in new_style
[03:58:23] [Wrapper/main/ERROR]     self.mcserver.events.call(
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/events.py", line 16, in call
[03:58:23] [Wrapper/main/ERROR]     listener.callback(*args, **_kwargs)
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/__init__.py", line 63, in response
[03:58:23] [Wrapper/main/ERROR]     player.message(command_response)
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/player.py", line 234, in message
[03:58:23] [Wrapper/main/ERROR]     self.server.features.message(self.username, message)
[03:58:23] [Wrapper/main/ERROR]   File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/features.py", line 23, in message
[03:58:23] [Wrapper/main/ERROR]     if self.version >= 76:
[03:58:23] [Wrapper/main/ERROR] TypeError: '>=' not supported between instances of 'NoneType' and 'int'
[03:58:23] [Wrapper/main/ERROR] 
Traceback (most recent call last):
  File "start-wrapper.py", line 6, in <module>
    wrapper.start()
  File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/__init__.py", line 107, in start
    self.cleanup()
  File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/__init__.py", line 116, in cleanup
    self.server.stop(save=False)
  File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/__init__.py", line 184, in stop
    player.kick(reason)
  File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/player.py", line 242, in kick
    self.server.run(
  File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/__init__.py", line 155, in run
    self.mcserver.command(cmd)
  File "/home/l33tlinuxh4x0r/Downloads/mcwrapper/wrapper/server/mcserver/__init__.py", line 113, in command
    raise ServerStopped()
wrapper.exceptions.ServerStopped
```

**Comment by l33tlinuxh4x0r** [comment]
looks like if I use server console I can change gamemode but if I op myself and try it the server crashes.

**Comment by benbaptist** [comment]
Should be fixed in the latest source!

**Comment by benbaptist** [comment]
Thank you for the bug reports! They're greatly appericiated.
